services:
  app:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: eureciclo-avaliacao-2-app
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - mysql

  phpmyadmin:
    container_name: eureciclo-avaliacao-2-phpmyadmin
    image: phpmyadmin:5.2.2-apache
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=0
      - MEMORY_LIMIT=1024M
      - UPLOAD_LIMIT=1024M
      - MAX_EXECUTION_TIME=0
      - UPLOAD_LIMI= 6096K
    depends_on:
      - mysql

  mysql:
    container_name: eureciclo-avaliacao-2-mysql
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3

  rabbitmq:
    build:
      context: .docker/rabbitmq
      dockerfile: Dockerfile
    container_name: eureciclo-avaliacao-2-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
